// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockusecase

import (
	"context"

	"github.com/danielmesquitta/openfinance/internal/domain/usecase"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSyncExecutor creates a new instance of MockSyncExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSyncExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSyncExecutor {
	mock := &MockSyncExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSyncExecutor is an autogenerated mock type for the SyncExecutor type
type MockSyncExecutor struct {
	mock.Mock
}

type MockSyncExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSyncExecutor) EXPECT() *MockSyncExecutor_Expecter {
	return &MockSyncExecutor_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockSyncExecutor
func (_mock *MockSyncExecutor) Execute(ctx context.Context, input usecase.SyncInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.SyncInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSyncExecutor_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockSyncExecutor_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.SyncInput
func (_e *MockSyncExecutor_Expecter) Execute(ctx interface{}, input interface{}) *MockSyncExecutor_Execute_Call {
	return &MockSyncExecutor_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockSyncExecutor_Execute_Call) Run(run func(ctx context.Context, input usecase.SyncInput)) *MockSyncExecutor_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 usecase.SyncInput
		if args[1] != nil {
			arg1 = args[1].(usecase.SyncInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSyncExecutor_Execute_Call) Return(err error) *MockSyncExecutor_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSyncExecutor_Execute_Call) RunAndReturn(run func(ctx context.Context, input usecase.SyncInput) error) *MockSyncExecutor_Execute_Call {
	_c.Call.Return(run)
	return _c
}
