version: "2"
linters:
  default: fast
  disable:
    - cyclop
    - gocognit
    - funlen
    - lll
    - mnd
    - nakedret
    - nestif
    - depguard
    - wsl
    - gochecknoinits
    - testpackage
    - dupl
  enable:
    - revive
    - wrapcheck
  settings:
    revive:
      enable-all-rules: true
      rules:
        - name: cyclomatic
          arguments: [15]
        - name: cognitive-complexity
          arguments: [15]
        - name: add-constant
          arguments:
            - allow-strs: '""'
              allow-ints: "0,1"
              allow-floats: "0.0"
              ignore-funcs: "time.Date,time.AddDate,slog.Info,slog.Error"
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: unused-receiver
          disabled: true
        - name: nested-structs
          disabled: true
        - name: function-length
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: confusing-naming
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: argument-limit
          disabled: true
  exclusions:
    generated: strict

    rules:
      - path: _test\.go
        linters:
          - revive

      - path: internal/app/server/handler
        linters:
          - godoclint

      - path: internal/config/wire
        linters:
          - inamedparam
          - revive

      - path: internal/app/server/router
        text: "(argument-limit|add-constant)"
        linters:
          - revive

formatters:
  enable:
    - gofmt
    - goimports
    - golines
  settings:
    golines:
      max-len: 120
