version: "2"
linters:
  default: fast
  disable:
    - cyclop
    - gocognit
    - funlen
    - lll
    - mnd
    - nakedret
    - nestif
    - depguard
    - wsl
    - gochecknoinits
  enable:
    - revive
    - wrapcheck
  settings:
    revive:
      enable-all-rules: true
      rules:
        - name: line-length-limit
          arguments:
            - 120
        - name: cyclomatic
          arguments: [15]
        - name: cognitive-complexity
          arguments: [15]
        - name: add-constant
          arguments:
            - allow-strs: '""'
              allow-ints: "0,1"
              allow-floats: "0.0"
              ignore-funcs: "time.Date,time.AddDate"
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: unused-receiver
          disabled: true
        - name: nested-structs
          disabled: true
        - name: function-length
          disabled: true
formatters:
  enable:
    - gofmt
    - goimports
    - golines
