template: testify
formatter: goimports
force-file-write: true
packages:
  github.com/danielmesquitta/openfinance/internal/provider/companyapi:
    interfaces:
      APIProvider:
        config:
          dir: internal/provider/companyapi/mockcompanyapi
          filename: mockcompanyapi.go
          pkgname: mockcompanyapi
          structname: MockCompanyAPI
  github.com/danielmesquitta/openfinance/internal/provider/gpt:
    interfaces:
      Provider:
        config:
          dir: internal/provider/gpt/mockgpt
          filename: mockgpt.go
          pkgname: mockgpt
          structname: MockGPT
  github.com/danielmesquitta/openfinance/internal/provider/openfinance:
    interfaces:
      APIProvider:
        config:
          dir: internal/provider/openfinance/mockopenfinance
          filename: mockopenfinance.go
          pkgname: mockopenfinance
          structname: MockOpenFinance
  github.com/danielmesquitta/openfinance/internal/provider/sheet:
    interfaces:
      Provider:
        config:
          dir: internal/provider/sheet/mocksheet
          filename: mocksheet.go
          pkgname: mocksheet
          structname: MockSheet
  github.com/danielmesquitta/openfinance/internal/domain/usecase/ingest:
    interfaces:
      IngestExecutor:
        config:
          dir: internal/domain/usecase/mockingest
          filename: mockingest.go
          pkgname: mockingest
          structname: MockIngest
