// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocksheet

import (
	"context"

	"github.com/danielmesquitta/openfinance/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSheet creates a new instance of MockSheet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSheet(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSheet {
	mock := &MockSheet{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSheet is an autogenerated mock type for the Provider type
type MockSheet struct {
	mock.Mock
}

type MockSheet_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSheet) EXPECT() *MockSheet_Expecter {
	return &MockSheet_Expecter{mock: &_m.Mock}
}

// CreateTransactionsTable provides a mock function for the type MockSheet
func (_mock *MockSheet) CreateTransactionsTable(ctx context.Context, userID string, title string) (entity.Table, error) {
	ret := _mock.Called(ctx, userID, title)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransactionsTable")
	}

	var r0 entity.Table
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (entity.Table, error)); ok {
		return returnFunc(ctx, userID, title)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) entity.Table); ok {
		r0 = returnFunc(ctx, userID, title)
	} else {
		r0 = ret.Get(0).(entity.Table)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, title)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSheet_CreateTransactionsTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTransactionsTable'
type MockSheet_CreateTransactionsTable_Call struct {
	*mock.Call
}

// CreateTransactionsTable is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - title string
func (_e *MockSheet_Expecter) CreateTransactionsTable(ctx interface{}, userID interface{}, title interface{}) *MockSheet_CreateTransactionsTable_Call {
	return &MockSheet_CreateTransactionsTable_Call{Call: _e.mock.On("CreateTransactionsTable", ctx, userID, title)}
}

func (_c *MockSheet_CreateTransactionsTable_Call) Run(run func(ctx context.Context, userID string, title string)) *MockSheet_CreateTransactionsTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSheet_CreateTransactionsTable_Call) Return(table entity.Table, err error) *MockSheet_CreateTransactionsTable_Call {
	_c.Call.Return(table, err)
	return _c
}

func (_c *MockSheet_CreateTransactionsTable_Call) RunAndReturn(run func(ctx context.Context, userID string, title string) (entity.Table, error)) *MockSheet_CreateTransactionsTable_Call {
	_c.Call.Return(run)
	return _c
}

// InsertTransaction provides a mock function for the type MockSheet
func (_mock *MockSheet) InsertTransaction(ctx context.Context, userID string, tableID string, transaction entity.Transaction) error {
	ret := _mock.Called(ctx, userID, tableID, transaction)

	if len(ret) == 0 {
		panic("no return value specified for InsertTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, entity.Transaction) error); ok {
		r0 = returnFunc(ctx, userID, tableID, transaction)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSheet_InsertTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertTransaction'
type MockSheet_InsertTransaction_Call struct {
	*mock.Call
}

// InsertTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - tableID string
//   - transaction entity.Transaction
func (_e *MockSheet_Expecter) InsertTransaction(ctx interface{}, userID interface{}, tableID interface{}, transaction interface{}) *MockSheet_InsertTransaction_Call {
	return &MockSheet_InsertTransaction_Call{Call: _e.mock.On("InsertTransaction", ctx, userID, tableID, transaction)}
}

func (_c *MockSheet_InsertTransaction_Call) Run(run func(ctx context.Context, userID string, tableID string, transaction entity.Transaction)) *MockSheet_InsertTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 entity.Transaction
		if args[3] != nil {
			arg3 = args[3].(entity.Transaction)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSheet_InsertTransaction_Call) Return(err error) *MockSheet_InsertTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSheet_InsertTransaction_Call) RunAndReturn(run func(ctx context.Context, userID string, tableID string, transaction entity.Transaction) error) *MockSheet_InsertTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// ListTables provides a mock function for the type MockSheet
func (_mock *MockSheet) ListTables(ctx context.Context, userID string) ([]entity.Table, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListTables")
	}

	var r0 []entity.Table
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]entity.Table, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []entity.Table); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Table)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSheet_ListTables_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTables'
type MockSheet_ListTables_Call struct {
	*mock.Call
}

// ListTables is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockSheet_Expecter) ListTables(ctx interface{}, userID interface{}) *MockSheet_ListTables_Call {
	return &MockSheet_ListTables_Call{Call: _e.mock.On("ListTables", ctx, userID)}
}

func (_c *MockSheet_ListTables_Call) Run(run func(ctx context.Context, userID string)) *MockSheet_ListTables_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSheet_ListTables_Call) Return(tables []entity.Table, err error) *MockSheet_ListTables_Call {
	_c.Call.Return(tables, err)
	return _c
}

func (_c *MockSheet_ListTables_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]entity.Table, error)) *MockSheet_ListTables_Call {
	_c.Call.Return(run)
	return _c
}

// ListTransactions provides a mock function for the type MockSheet
func (_mock *MockSheet) ListTransactions(ctx context.Context, userID string, tableID string) ([]entity.Transaction, error) {
	ret := _mock.Called(ctx, userID, tableID)

	if len(ret) == 0 {
		panic("no return value specified for ListTransactions")
	}

	var r0 []entity.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]entity.Transaction, error)); ok {
		return returnFunc(ctx, userID, tableID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []entity.Transaction); ok {
		r0 = returnFunc(ctx, userID, tableID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, tableID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSheet_ListTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTransactions'
type MockSheet_ListTransactions_Call struct {
	*mock.Call
}

// ListTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - tableID string
func (_e *MockSheet_Expecter) ListTransactions(ctx interface{}, userID interface{}, tableID interface{}) *MockSheet_ListTransactions_Call {
	return &MockSheet_ListTransactions_Call{Call: _e.mock.On("ListTransactions", ctx, userID, tableID)}
}

func (_c *MockSheet_ListTransactions_Call) Run(run func(ctx context.Context, userID string, tableID string)) *MockSheet_ListTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSheet_ListTransactions_Call) Return(transactions []entity.Transaction, err error) *MockSheet_ListTransactions_Call {
	_c.Call.Return(transactions, err)
	return _c
}

func (_c *MockSheet_ListTransactions_Call) RunAndReturn(run func(ctx context.Context, userID string, tableID string) ([]entity.Transaction, error)) *MockSheet_ListTransactions_Call {
	_c.Call.Return(run)
	return _c
}
