// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocksheet

import (
	"context"

	"github.com/danielmesquitta/openfinance/internal/provider/sheet"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSheet creates a new instance of MockSheet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSheet(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSheet {
	mock := &MockSheet{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSheet is an autogenerated mock type for the Provider type
type MockSheet struct {
	mock.Mock
}

type MockSheet_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSheet) EXPECT() *MockSheet_Expecter {
	return &MockSheet_Expecter{mock: &_m.Mock}
}

// CreateTable provides a mock function for the type MockSheet
func (_mock *MockSheet) CreateTable(ctx context.Context, connectionID string, title string, options ...sheet.CreateTableOption) (sheet.Table, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, connectionID, title, options)
	} else {
		tmpRet = _mock.Called(ctx, connectionID, title)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateTable")
	}

	var r0 sheet.Table
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...sheet.CreateTableOption) (sheet.Table, error)); ok {
		return returnFunc(ctx, connectionID, title, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...sheet.CreateTableOption) sheet.Table); ok {
		r0 = returnFunc(ctx, connectionID, title, options...)
	} else {
		r0 = ret.Get(0).(sheet.Table)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, ...sheet.CreateTableOption) error); ok {
		r1 = returnFunc(ctx, connectionID, title, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSheet_CreateTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTable'
type MockSheet_CreateTable_Call struct {
	*mock.Call
}

// CreateTable is a helper method to define mock.On call
//   - ctx context.Context
//   - connectionID string
//   - title string
//   - options ...sheet.CreateTableOption
func (_e *MockSheet_Expecter) CreateTable(ctx interface{}, connectionID interface{}, title interface{}, options ...interface{}) *MockSheet_CreateTable_Call {
	return &MockSheet_CreateTable_Call{Call: _e.mock.On("CreateTable",
		append([]interface{}{ctx, connectionID, title}, options...)...)}
}

func (_c *MockSheet_CreateTable_Call) Run(run func(ctx context.Context, connectionID string, title string, options ...sheet.CreateTableOption)) *MockSheet_CreateTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []sheet.CreateTableOption
		var variadicArgs []sheet.CreateTableOption
		if len(args) > 3 {
			variadicArgs = args[3].([]sheet.CreateTableOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockSheet_CreateTable_Call) Return(table sheet.Table, err error) *MockSheet_CreateTable_Call {
	_c.Call.Return(table, err)
	return _c
}

func (_c *MockSheet_CreateTable_Call) RunAndReturn(run func(ctx context.Context, connectionID string, title string, options ...sheet.CreateTableOption) (sheet.Table, error)) *MockSheet_CreateTable_Call {
	_c.Call.Return(run)
	return _c
}

// InsertRow provides a mock function for the type MockSheet
func (_mock *MockSheet) InsertRow(ctx context.Context, connectionID string, tableID string, row sheet.Row) error {
	ret := _mock.Called(ctx, connectionID, tableID, row)

	if len(ret) == 0 {
		panic("no return value specified for InsertRow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, sheet.Row) error); ok {
		r0 = returnFunc(ctx, connectionID, tableID, row)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSheet_InsertRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertRow'
type MockSheet_InsertRow_Call struct {
	*mock.Call
}

// InsertRow is a helper method to define mock.On call
//   - ctx context.Context
//   - connectionID string
//   - tableID string
//   - row sheet.Row
func (_e *MockSheet_Expecter) InsertRow(ctx interface{}, connectionID interface{}, tableID interface{}, row interface{}) *MockSheet_InsertRow_Call {
	return &MockSheet_InsertRow_Call{Call: _e.mock.On("InsertRow", ctx, connectionID, tableID, row)}
}

func (_c *MockSheet_InsertRow_Call) Run(run func(ctx context.Context, connectionID string, tableID string, row sheet.Row)) *MockSheet_InsertRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 sheet.Row
		if args[3] != nil {
			arg3 = args[3].(sheet.Row)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSheet_InsertRow_Call) Return(err error) *MockSheet_InsertRow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSheet_InsertRow_Call) RunAndReturn(run func(ctx context.Context, connectionID string, tableID string, row sheet.Row) error) *MockSheet_InsertRow_Call {
	_c.Call.Return(run)
	return _c
}

// ListRows provides a mock function for the type MockSheet
func (_mock *MockSheet) ListRows(ctx context.Context, connectionID string, tableID string) ([]sheet.Row, error) {
	ret := _mock.Called(ctx, connectionID, tableID)

	if len(ret) == 0 {
		panic("no return value specified for ListRows")
	}

	var r0 []sheet.Row
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]sheet.Row, error)); ok {
		return returnFunc(ctx, connectionID, tableID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []sheet.Row); ok {
		r0 = returnFunc(ctx, connectionID, tableID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sheet.Row)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, connectionID, tableID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSheet_ListRows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRows'
type MockSheet_ListRows_Call struct {
	*mock.Call
}

// ListRows is a helper method to define mock.On call
//   - ctx context.Context
//   - connectionID string
//   - tableID string
func (_e *MockSheet_Expecter) ListRows(ctx interface{}, connectionID interface{}, tableID interface{}) *MockSheet_ListRows_Call {
	return &MockSheet_ListRows_Call{Call: _e.mock.On("ListRows", ctx, connectionID, tableID)}
}

func (_c *MockSheet_ListRows_Call) Run(run func(ctx context.Context, connectionID string, tableID string)) *MockSheet_ListRows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSheet_ListRows_Call) Return(rows []sheet.Row, err error) *MockSheet_ListRows_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *MockSheet_ListRows_Call) RunAndReturn(run func(ctx context.Context, connectionID string, tableID string) ([]sheet.Row, error)) *MockSheet_ListRows_Call {
	_c.Call.Return(run)
	return _c
}

// ListTables provides a mock function for the type MockSheet
func (_mock *MockSheet) ListTables(ctx context.Context, connectionID string) ([]sheet.Table, error) {
	ret := _mock.Called(ctx, connectionID)

	if len(ret) == 0 {
		panic("no return value specified for ListTables")
	}

	var r0 []sheet.Table
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]sheet.Table, error)); ok {
		return returnFunc(ctx, connectionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []sheet.Table); ok {
		r0 = returnFunc(ctx, connectionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sheet.Table)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, connectionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSheet_ListTables_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTables'
type MockSheet_ListTables_Call struct {
	*mock.Call
}

// ListTables is a helper method to define mock.On call
//   - ctx context.Context
//   - connectionID string
func (_e *MockSheet_Expecter) ListTables(ctx interface{}, connectionID interface{}) *MockSheet_ListTables_Call {
	return &MockSheet_ListTables_Call{Call: _e.mock.On("ListTables", ctx, connectionID)}
}

func (_c *MockSheet_ListTables_Call) Run(run func(ctx context.Context, connectionID string)) *MockSheet_ListTables_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSheet_ListTables_Call) Return(tables []sheet.Table, err error) *MockSheet_ListTables_Call {
	_c.Call.Return(tables, err)
	return _c
}

func (_c *MockSheet_ListTables_Call) RunAndReturn(run func(ctx context.Context, connectionID string) ([]sheet.Table, error)) *MockSheet_ListTables_Call {
	_c.Call.Return(run)
	return _c
}
