// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcompanyapi

import (
	"context"

	"github.com/danielmesquitta/openfinance-to-sheets/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCompanyAPI creates a new instance of MockCompanyAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCompanyAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCompanyAPI {
	mock := &MockCompanyAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCompanyAPI is an autogenerated mock type for the APIProvider type
type MockCompanyAPI struct {
	mock.Mock
}

type MockCompanyAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCompanyAPI) EXPECT() *MockCompanyAPI_Expecter {
	return &MockCompanyAPI_Expecter{mock: &_m.Mock}
}

// GetCompanyByID provides a mock function for the type MockCompanyAPI
func (_mock *MockCompanyAPI) GetCompanyByID(ctx context.Context, id string) (entity.Company, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCompanyByID")
	}

	var r0 entity.Company
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entity.Company, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entity.Company); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Company)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCompanyAPI_GetCompanyByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompanyByID'
type MockCompanyAPI_GetCompanyByID_Call struct {
	*mock.Call
}

// GetCompanyByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCompanyAPI_Expecter) GetCompanyByID(ctx interface{}, id interface{}) *MockCompanyAPI_GetCompanyByID_Call {
	return &MockCompanyAPI_GetCompanyByID_Call{Call: _e.mock.On("GetCompanyByID", ctx, id)}
}

func (_c *MockCompanyAPI_GetCompanyByID_Call) Run(run func(ctx context.Context, id string)) *MockCompanyAPI_GetCompanyByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCompanyAPI_GetCompanyByID_Call) Return(company entity.Company, err error) *MockCompanyAPI_GetCompanyByID_Call {
	_c.Call.Return(company, err)
	return _c
}

func (_c *MockCompanyAPI_GetCompanyByID_Call) RunAndReturn(run func(ctx context.Context, id string) (entity.Company, error)) *MockCompanyAPI_GetCompanyByID_Call {
	_c.Call.Return(run)
	return _c
}
