// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgpt

import (
	"context"

	"github.com/danielmesquitta/openfinance-to-sheets/internal/provider/gpt"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGPT creates a new instance of MockGPT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGPT(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGPT {
	mock := &MockGPT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGPT is an autogenerated mock type for the Provider type
type MockGPT struct {
	mock.Mock
}

type MockGPT_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGPT) EXPECT() *MockGPT_Expecter {
	return &MockGPT_Expecter{mock: &_m.Mock}
}

// CreateChatCompletion provides a mock function for the type MockGPT
func (_mock *MockGPT) CreateChatCompletion(ctx context.Context, message string, options ...gpt.ChatCompletionOption) (string, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, message, options)
	} else {
		tmpRet = _mock.Called(ctx, message)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateChatCompletion")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...gpt.ChatCompletionOption) (string, error)); ok {
		return returnFunc(ctx, message, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...gpt.ChatCompletionOption) string); ok {
		r0 = returnFunc(ctx, message, options...)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...gpt.ChatCompletionOption) error); ok {
		r1 = returnFunc(ctx, message, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGPT_CreateChatCompletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChatCompletion'
type MockGPT_CreateChatCompletion_Call struct {
	*mock.Call
}

// CreateChatCompletion is a helper method to define mock.On call
//   - ctx context.Context
//   - message string
//   - options ...gpt.ChatCompletionOption
func (_e *MockGPT_Expecter) CreateChatCompletion(ctx interface{}, message interface{}, options ...interface{}) *MockGPT_CreateChatCompletion_Call {
	return &MockGPT_CreateChatCompletion_Call{Call: _e.mock.On("CreateChatCompletion",
		append([]interface{}{ctx, message}, options...)...)}
}

func (_c *MockGPT_CreateChatCompletion_Call) Run(run func(ctx context.Context, message string, options ...gpt.ChatCompletionOption)) *MockGPT_CreateChatCompletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []gpt.ChatCompletionOption
		var variadicArgs []gpt.ChatCompletionOption
		if len(args) > 2 {
			variadicArgs = args[2].([]gpt.ChatCompletionOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockGPT_CreateChatCompletion_Call) Return(s string, err error) *MockGPT_CreateChatCompletion_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGPT_CreateChatCompletion_Call) RunAndReturn(run func(ctx context.Context, message string, options ...gpt.ChatCompletionOption) (string, error)) *MockGPT_CreateChatCompletion_Call {
	_c.Call.Return(run)
	return _c
}
