definitions:
  dto.ErrorResponseDTO:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /to-notion:
    post:
      consumes:
      - application/json
      description: This endpoint is responsible for syncing OpenFinance data to Notion.
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
      summary: OpenFinance to Notion.
      tags:
      - Notion
swagger: "2.0"
