// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/danielmesquitta/openfinance-to-sheets/internal/config"
	"github.com/danielmesquitta/openfinance-to-sheets/internal/domain/entity"
	"github.com/danielmesquitta/openfinance-to-sheets/internal/domain/usecase/ingest"
	"github.com/danielmesquitta/openfinance-to-sheets/internal/pkg/validator"
	"github.com/danielmesquitta/openfinance-to-sheets/internal/provider/companyapi/brasilapi"
	"github.com/danielmesquitta/openfinance-to-sheets/internal/provider/gpt/openai"
	"github.com/danielmesquitta/openfinance-to-sheets/internal/provider/openfinance/pluggyapi"
	"github.com/danielmesquitta/openfinance-to-sheets/internal/provider/sheet/notionapi"
)

// Injectors from wire.go:

func NewIngestUseCase() (*ingest.Ingest, error) {
	validatorValidator := validator.NewValidator()
	env, err := config.NewEnv(validatorValidator)
	if err != nil {
		return nil, err
	}
	int2 := maxConcurrentOperations(env)
	entityIngestSettings := ingestSettings(env)
	client := brasilapi.NewClient()
	openAIClient := openai.NewOpenAIClient(env)
	notionapiClient := notionapi.NewClient(env)
	pluggyapiClient, err := pluggyapi.NewClient(env)
	if err != nil {
		return nil, err
	}
	ingestIngest := ingest.NewIngest(validatorValidator, int2, entityIngestSettings, client, openAIClient, notionapiClient, pluggyapiClient)
	return ingestIngest, nil
}

// wire.go:

func ingestSettings(env *config.Env) entity.IngestSettings {
	return env.IngestSettings
}

func maxConcurrentOperations(env *config.Env) int {
	return env.MaxConcurrentOperations
}
