// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/danielmesquitta/openfinance/internal/config"
	"github.com/danielmesquitta/openfinance/internal/domain/usecase"
	"github.com/danielmesquitta/openfinance/internal/pkg/validator"
	"github.com/danielmesquitta/openfinance/internal/provider/companyapi/brasilapi"
	"github.com/danielmesquitta/openfinance/internal/provider/gpt/openai"
	"github.com/danielmesquitta/openfinance/internal/provider/openfinance/pluggyapi"
	"github.com/danielmesquitta/openfinance/internal/provider/sheet/notionapi"
)

// Injectors from wire.go:

func NewSyncAllUseCase() *usecase.SyncAll {
	validatorValidator := validator.NewValidator()
	env := config.NewEnv(validatorValidator)
	client := brasilapi.NewClient()
	openAIClient := openai.NewOpenAIClient(env)
	notionapiClient := notionapi.NewClient(env)
	pluggyapiClient := pluggyapi.NewClient(env)
	syncOne := usecase.NewSyncOne(validatorValidator, client, openAIClient, notionapiClient, pluggyapiClient)
	syncAll := usecase.NewSyncAll(validatorValidator, env, syncOne)
	return syncAll
}
