// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/danielmesquitta/openfinance/internal/config"
	"github.com/danielmesquitta/openfinance/internal/domain/entity"
	"github.com/danielmesquitta/openfinance/internal/domain/usecase"
	"github.com/danielmesquitta/openfinance/internal/pkg/validator"
	"github.com/danielmesquitta/openfinance/internal/provider/companyapi/brasilapi"
	"github.com/danielmesquitta/openfinance/internal/provider/gpt/openai"
	"github.com/danielmesquitta/openfinance/internal/provider/openfinance/pluggyapi"
	"github.com/danielmesquitta/openfinance/internal/provider/sheet/notionapi"
)

// Injectors from wire.go:

func NewSyncUseCase() (*usecase.Sync, error) {
	validatorValidator := validator.NewValidator()
	env, err := config.NewEnv(validatorValidator)
	if err != nil {
		return nil, err
	}
	int2 := maxConcurrentOperations(env)
	entitySyncSettings := syncSettings(env)
	client := brasilapi.NewClient()
	openAIClient := openai.NewOpenAIClient(env)
	notionapiClient := notionapi.NewClient(env)
	pluggyapiClient, err := pluggyapi.NewClient(env)
	if err != nil {
		return nil, err
	}
	sync := usecase.NewSync(int2, entitySyncSettings, client, openAIClient, notionapiClient, pluggyapiClient)
	return sync, nil
}

// wire.go:

func syncSettings(env *config.Env) entity.SyncSettings {
	return env.SyncSettings
}

func maxConcurrentOperations(env *config.Env) int {
	return env.MaxConcurrentOperations
}
