// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockopenfinance

import (
	"context"
	"time"

	"github.com/danielmesquitta/openfinance/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOpenFinance creates a new instance of MockOpenFinance. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOpenFinance(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOpenFinance {
	mock := &MockOpenFinance{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOpenFinance is an autogenerated mock type for the APIProvider type
type MockOpenFinance struct {
	mock.Mock
}

type MockOpenFinance_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOpenFinance) EXPECT() *MockOpenFinance_Expecter {
	return &MockOpenFinance_Expecter{mock: &_m.Mock}
}

// ListTransactionsBySyncProfileID provides a mock function for the type MockOpenFinance
func (_mock *MockOpenFinance) ListTransactionsBySyncProfileID(ctx context.Context, syncProfileID string, from time.Time, to time.Time) ([]entity.Transaction, error) {
	ret := _mock.Called(ctx, syncProfileID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ListTransactionsBySyncProfileID")
	}

	var r0 []entity.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]entity.Transaction, error)); ok {
		return returnFunc(ctx, syncProfileID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []entity.Transaction); ok {
		r0 = returnFunc(ctx, syncProfileID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, syncProfileID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOpenFinance_ListTransactionsBySyncProfileID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTransactionsBySyncProfileID'
type MockOpenFinance_ListTransactionsBySyncProfileID_Call struct {
	*mock.Call
}

// ListTransactionsBySyncProfileID is a helper method to define mock.On call
//   - ctx context.Context
//   - syncProfileID string
//   - from time.Time
//   - to time.Time
func (_e *MockOpenFinance_Expecter) ListTransactionsBySyncProfileID(ctx interface{}, syncProfileID interface{}, from interface{}, to interface{}) *MockOpenFinance_ListTransactionsBySyncProfileID_Call {
	return &MockOpenFinance_ListTransactionsBySyncProfileID_Call{Call: _e.mock.On("ListTransactionsBySyncProfileID", ctx, syncProfileID, from, to)}
}

func (_c *MockOpenFinance_ListTransactionsBySyncProfileID_Call) Run(run func(ctx context.Context, syncProfileID string, from time.Time, to time.Time)) *MockOpenFinance_ListTransactionsBySyncProfileID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOpenFinance_ListTransactionsBySyncProfileID_Call) Return(transactions []entity.Transaction, err error) *MockOpenFinance_ListTransactionsBySyncProfileID_Call {
	_c.Call.Return(transactions, err)
	return _c
}

func (_c *MockOpenFinance_ListTransactionsBySyncProfileID_Call) RunAndReturn(run func(ctx context.Context, syncProfileID string, from time.Time, to time.Time) ([]entity.Transaction, error)) *MockOpenFinance_ListTransactionsBySyncProfileID_Call {
	_c.Call.Return(run)
	return _c
}
