// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockingest

import (
	"context"

	"github.com/danielmesquitta/openfinance-to-sheets/internal/domain/usecase/ingest"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIngest creates a new instance of MockIngest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIngest(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIngest {
	mock := &MockIngest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIngest is an autogenerated mock type for the IngestExecutor type
type MockIngest struct {
	mock.Mock
}

type MockIngest_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIngest) EXPECT() *MockIngest_Expecter {
	return &MockIngest_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockIngest
func (_mock *MockIngest) Execute(ctx context.Context, input ingest.IngestInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ingest.IngestInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIngest_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockIngest_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input ingest.IngestInput
func (_e *MockIngest_Expecter) Execute(ctx interface{}, input interface{}) *MockIngest_Execute_Call {
	return &MockIngest_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockIngest_Execute_Call) Run(run func(ctx context.Context, input ingest.IngestInput)) *MockIngest_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ingest.IngestInput
		if args[1] != nil {
			arg1 = args[1].(ingest.IngestInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIngest_Execute_Call) Return(err error) *MockIngest_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIngest_Execute_Call) RunAndReturn(run func(ctx context.Context, input ingest.IngestInput) error) *MockIngest_Execute_Call {
	_c.Call.Return(run)
	return _c
}
