name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.25.2'

    - name: Set up env
      run: |
        cat > .env << 'EOF'
        ${{ secrets.ENV }}
        EOF
        cat > config/categories.json << 'EOF'
        ${{ secrets.CATEGORIES_JSON }}
        EOF
        cat > config/mappings.json << 'EOF'
        ${{ secrets.MAPPINGS_JSON }}
        EOF
        cat > config/users.json << 'EOF'
        ${{ secrets.USERS_JSON }}
        EOF

    - name: Install dependencies
      run: make install

    - name: Build the Go binary
      run: make build

    - name: Zip the binary
      run: make zip

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code --function-name openfinance-to-notion --zip-file fileb://tmp/lambda.zip
